### ISSUE TITLE
エラーログ

### ISSUE THREAD

**Issue by aimerci** [panchan-source/wellnote-download#1]
はじめまして。この度は素晴らしいツールありがとうございます。取得中のエラーをお送りします。
再実行しても同じエラー（line）で停止します。
![スクリーンショット 2022-12-11 132947](https://user-images.githubusercontent.com/31067192/206886689-20794a0b-2be4-4c9a-afb9-e347101756a8.png)

**Comment by panchan-source** [comment]
ご報告ありがとございます。
このバージョンはGitからダウンロードしたバージョンでしょうか？
現在の最新バージョンは1.1ですのでまだお試しいただいてなければ一度最新版でお試しをお願いします。

**Comment by aimerci** [comment]
ご指示ありがとうございます。
1.1ダウンロードし直したところ、起動時に別のエラー文が出てすぐクラッシュしました。（ログイン画面が出る前）
Windows再起動や関連ファイルを削除し再実行しましたが、同じでした。
<img width="1017" alt="スクリーンショット 2022-12-11 14 02 24" src="https://user-images.githubusercontent.com/31067192/206887389-7bbc0bfc-0d4a-44ca-a227-fa76882b84b2.png">

**Comment by panchan-source** [comment]
昨日追加したコードにバグがあったので修正しました💦
Ver1.1.1をお試しくださいー

**Comment by aimerci** [comment]
早々のご対応をありがとうございます！
無事ログインできて、前回エラーで止まったところも超えて取得が続いていますので、一旦closeさせてください！重ねて素晴らしいツールをありがとうございます。

**Comment by panchan-source** [comment]
よかったです！
私はもともとwellnoteを使っていなかったので、考慮が漏れているシナリオがあったらご連絡ください！
