### ISSUE TITLE
v1.2.0 pages(html生成)でエラー

### ISSUE THREAD

**Issue by aimerci** [panchan-source/wellnote-download#2]
続けてすみません。画像・動画など全て無事取得でき大変助かりました。

[v1.2.0](https://github.com/panchan-source/wellnote-download/releases/tag/v1.2.0)
1.2.0で実行していたのですが、html生成時にエラーが出ました。
![スクリーンショット 2022-12-12 013557](https://user-images.githubusercontent.com/31067192/206917885-71f28eb0-3a4f-4280-8dda-86930fde35bb.png)

明日以降、1.3.x以降で試してみます。

**Comment by panchan-source** [comment]
ご報告ありがとうございます。
私の知らないタイプの成長記録のデータがきているようなのでもしよろしければDMなどでcontents/rawdata/配下のtweets_{familyid}_x.jsonの中から画像上のid(01cxdで始まるID)で検索して該当データをいただくことは可能でしょうか？

**Comment by panchan-source** [comment]
個人情報に関係する部分は適当な文字列に変えていただいて問題ございません

**Comment by aimerci** [comment]
ご返信ありがとうございます。
該当データを特定しました。TwitterのDM、自分は開放しているので差し支えなければ一言いただければ幸いです。

**Comment by panchan-source** [comment]
v1.4.0で改善しているかと思うので、なおっていたらご連絡下さい！
